### ISSUE TITLE
Node.js v4

### ISSUE THREAD

**Issue by mbrevda** [wercker/box-nodejs#5]
Now that Node.js v4 (which is the merge with io.js) is out, it would be helpful to get this box updated. Thanks!

**Comment by qraynaud** [comment]
Yes, I need this too!

**Comment by ptarjan** [comment]
:+1:

**Comment by xeodou** [comment]
:+1:

**Comment by rolandjitsu** [comment]
Note that node is now at version 5. And it requires a C++11 standard compliant compiler (I use gcc 4.8 on my machine).

**Comment by rolandjitsu** [comment]
But, as I can see from [getting-started-with-nodejs](https://github.com/wercker/getting-started-nodejs), the `wercker.yml`:
```yml
box: nodesource/trusty
dev:
  steps:
    - npm-install
    - internal/watch:
        code: node app.js
        reload: true

# Build definition
build:
  # The steps that will be executed on build
  steps:
    - script:
        code: export NODE_ENV='testing'
    # A step that executes `npm install` command
    - npm-install
    # A step that executes `npm test` command
    - npm-test

    # A custom script step, name value is used in the UI
    # and the code value contains the command that get executed
    - script:
        name: echo nodejs information
        code: |
          echo "node version $(node -v) running"
          echo "npm version $(npm -v) running"
```
Points to the box `nodesource/trusty`, does this mean I could also use some of the other nodesource boxes, like `nodesource/wheezy` which provides the latest versions of node?
